# Generated by Django 5.2.4 on 2025-09-19 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cumpleaños',
                'verbose_name_plural': 'Cumpleaños',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de Ausencia')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requiere Aprobación')),
                ('paid', models.BooleanField(default=True, verbose_name='Con Goce de Sueldo')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Color (HEX)')),
            ],
            options={
                'verbose_name': 'Tipo de Ausencia',
                'verbose_name_plural': 'Tipos de Ausencia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID de Empleado')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Móvil')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('hire_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Contacto de Emergencia')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Emergencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.absencetype', verbose_name='Tipo de Ausencia')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='team.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Ausencia',
                'verbose_name_plural': 'Ausencias',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('days_entitled', models.IntegerField(default=0, verbose_name='Días Correspondientes')),
                ('days_taken', models.IntegerField(default=0, verbose_name='Días Tomados')),
                ('days_pending', models.IntegerField(default=0, verbose_name='Días Pendientes')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='team.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Control de Vacaciones',
                'verbose_name_plural': 'Control de Vacaciones',
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
