# Generated by Django 5.2.4 on 2025-09-19 12:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('OPERATIONAL', 'Operativo'), ('PROJECT', 'Proyecto'), ('INITIATIVE', 'Iniciativa'), ('IMPROVEMENT', 'Mejora'), ('SUPPORT', 'Soporte')], max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Color (HEX)')),
            ],
            options={
                'verbose_name': 'Tipo de Iniciativa',
                'verbose_name_plural': 'Tipos de Iniciativa',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('PLANNED', 'Planeado'), ('IN_PROGRESS', 'En Progreso'), ('BLOCKED', 'Bloqueado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='BACKLOG', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Prioridad')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Fecha Objetivo')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso (%)')),
                ('is_operational', models.BooleanField(default=False, verbose_name='Es Operativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_initiatives', to='team.employee', verbose_name='Colaboradores')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_initiatives', to='team.employee', verbose_name='Responsable')),
                ('initiative_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='initiatives.initiativetype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Iniciativa',
                'verbose_name_plural': 'Iniciativas',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='Nombre de la Métrica')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Objetivo')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Actual')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unidad')),
                ('measured_at', models.DateField(default=datetime.date.today, verbose_name='Fecha de Medición')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='initiatives.initiative', verbose_name='Iniciativa')),
            ],
            options={
                'verbose_name': 'Métrica de Iniciativa',
                'verbose_name_plural': 'Métricas de Iniciativas',
                'ordering': ['initiative', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('PROGRESS', 'Actualización de Progreso'), ('BLOCKER', 'Bloqueo'), ('RISK', 'Riesgo'), ('ACHIEVEMENT', 'Logro'), ('COMMENT', 'Comentario')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='initiatives.initiative', verbose_name='Iniciativa')),
            ],
            options={
                'verbose_name': 'Actualización de Iniciativa',
                'verbose_name_plural': 'Actualizaciones de Iniciativas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual'), ('ON_DEMAND', 'Bajo Demanda')], max_length=20, verbose_name='Frecuencia')),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Lunes, 6=Domingo', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Día de la Semana')),
                ('day_of_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día del Mes')),
                ('time_of_day', models.TimeField(blank=True, null=True, verbose_name='Hora del Día')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Duración (horas)')),
                ('last_execution', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('next_execution', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Ejecución')),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_details', to='initiatives.initiative', verbose_name='Iniciativa')),
            ],
            options={
                'verbose_name': 'Tarea Operativa',
                'verbose_name_plural': 'Tareas Operativas',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Trimestre')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Periodo (Q)',
                'verbose_name_plural': 'Periodos (Q)',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.AddField(
            model_name='initiative',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='initiatives.quarter', verbose_name='Periodo (Q)'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sprint_number', models.IntegerField(verbose_name='Número de Sprint')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('goal', models.TextField(blank=True, verbose_name='Objetivo del Sprint')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='initiatives.quarter', verbose_name='Periodo (Q)')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['quarter', 'sprint_number'],
                'unique_together': {('quarter', 'sprint_number')},
            },
        ),
    ]
