# Generated by Django 5.2.4 on 2025-09-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('acceptance_criteria', models.TextField(blank=True, verbose_name='Criterios de Aceptación')),
                ('story_points', models.IntegerField(blank=True, choices=[(1, '1 - Muy Pequeña'), (2, '2 - Pequeña'), (3, '3 - Mediana'), (5, '5 - Grande'), (8, '8 - Muy Grande'), (13, '13 - Extra Grande'), (21, '21 - XXL')], null=True, verbose_name='Story Points')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('READY', 'Listo para Sprint'), ('IN_PROGRESS', 'En Progreso'), ('IN_REVIEW', 'En Revisión'), ('TESTING', 'Pruebas'), ('DONE', 'Terminado'), ('CANCELLED', 'Cancelado')], default='BACKLOG', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stories', to='team.employee', verbose_name='Asignado a')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='initiatives.initiative', verbose_name='Iniciativa (Épica)')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to='initiatives.sprint', verbose_name='Sprint')),
            ],
            options={
                'verbose_name': 'Historia de Usuario',
                'verbose_name_plural': 'Historias de Usuario',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('task_type', models.CharField(choices=[('DEVELOPMENT', 'Desarrollo'), ('TESTING', 'Pruebas'), ('DESIGN', 'Diseño'), ('RESEARCH', 'Investigación'), ('DOCUMENTATION', 'Documentación'), ('REVIEW', 'Revisión'), ('DEPLOYMENT', 'Despliegue'), ('OTHER', 'Otro')], default='DEVELOPMENT', max_length=20, verbose_name='Tipo de Tarea')),
                ('status', models.CharField(choices=[('TODO', 'Por Hacer'), ('IN_PROGRESS', 'En Progreso'), ('IN_REVIEW', 'En Revisión'), ('DONE', 'Terminado'), ('BLOCKED', 'Bloqueado')], default='TODO', max_length=20, verbose_name='Estado')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Estimadas')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Reales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado el')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('blocked_reason', models.TextField(blank=True, verbose_name='Razón del Bloqueo')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='team.employee', verbose_name='Asignado a')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='initiatives.userstory', verbose_name='Historia de Usuario')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
